stringOperand =
    FieldIdentifierString | StringLiteral | castToString | SingleAttribute ;
 
numericalOperand =
    NumericalLiteral | castToNumerical | dateTimeToNum ;
 
hexOperand =
    HexLiteral | castToHex ;

boolOperand =
    BoolLiteral | castToBool ;
 
dateTimeOperand =
    DateTimeLiteral | castToDateTime | GlobalAttribute ;
 
timeOperand =
    TimeLiteral | castToTime ;
 
castToString =
    "str",  ws, "(",  ws, operand, ws, ")", ws ;
 
castToNumerical =
    "num",  ws, "(",  ws, operand, ws, ")", ws ;
 
castToHex =
    "hex",  ws, "(",  ws, operand, ws, ")", ws ;
 
castToBool =
    "bool",  ws, "(",  ws, operand, ws, ")", ws ;
 
castToDateTime =
    "dateTime",  ws, "(",  ws, stringOperand, ws, ")",  ws ;