year = digit, ws, digit, ws, digit, ws, digit, ws ;
month = digit, ws, digit, ws ;
day = digit, ws, digit, ws ;
time = hour, ws, ":", ws, minute, ws, { ":", ws, second, ws }, { ".", ws, fraction, ws } ;
timezone = ( "Z" | ( "+" | "-" ), ws, hour, ws, ":", ws, minute, ws ) ;
hour = digit, ws, digit, ws ;
minute = digit, ws, digit, ws ;
second = digit, ws, digit, ws ;
fraction = digit, { digit }, ws ;

digit = ( "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" ) ;
digitWs = digit, ws ;
UpperAtoZ = "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" | "J"
          | "K" | "L" | "M" | "N" | "O" | "P" | "Q" | "R" | "S" | "T"
          | "U" | "V" | "W" | "X" | "Y" | "Z" ;
UpperAtoF = "A" | "B" | "C" | "D" | "E" | "F" ;
LowerAtoZ = "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" | "j"
          | "k" | "l" | "m" | "n" | "o" | "p" | "q" | "r" | "s" | "t"
          | "u" | "v" | "w" | "x" | "y" | "z" ;